"""Convert and evaluate a human-labelled Android/AR holdout batch.

Expected input is the confirmed keypoint incoming layout:

    data/incoming/ar_device_holdout/
      images/<stem>.jpg
      annotations/<stem>.json

The command converts the whole batch into a validation-only YOLO-pose
dataset, writes a temporary dataset config outside `configs/` so it does
not pollute the training dataset audit, evaluates the champion model, and
writes `outputs/production_audit/ar_device_holdout_eval.json` for the
production gate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any


DEFAULT_SOURCE_ROOT = Path("data/incoming/ar_device_holdout")
DEFAULT_DATASET_ROOT = Path("data/wheel_pose_dataset_ar_device_holdout")
DEFAULT_CONFIG_OUT = Path("outputs/production_audit/ar_device_holdout_dataset.yaml")
DEFAULT_EVAL_OUT = Path("outputs/production_audit/ar_device_holdout_eval.json")
DEFAULT_STATUS_OUT = Path("outputs/production_audit/ar_device_holdout_pipeline.json")
DEFAULT_MODEL = Path("runs/pose/wheel_real_v1_self_plus_ue_synthetic_s/weights/best.pt")

PROVENANCE_CANDIDATES = (
    Path("metadata/provenance.json"),
    Path("metadata/source_info.json"),
)
PRODUCTION_SOURCE_TYPES = {
    "ar_device_human_labelled",
    "android_ar_device_human_labelled",
    "ios_ar_device_human_labelled",
}
PRODUCTION_LABEL_TYPE = "human_reviewed"
EXPECTED_PROVENANCE_SCHEMA_VERSION = 1
EXPECTED_ANNOTATION_SCHEMA_VERSION = 1
PRODUCTION_REQUIRED_POINTS = ("a", "b", "c_disc_bottom")
UTC_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def is_placeholder(value: str) -> bool:
    normalized = value.strip().lower()
    return not normalized or "fill_me" in normalized or normalized in {"todo", "tbd", "unknown"}


def is_valid_utc_date(value: str) -> bool:
    if not UTC_DATE_RE.match(value):
        return False
    try:
        parsed = date.fromisoformat(value)
    except ValueError:
        return False
    return parsed <= date.today()


def schema_version_matches(value: Any, expected: int) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value == expected


def write_dataset_config(path: Path, dataset_root: Path) -> None:
    text = f"""# Auto-generated by src/evaluate_ar_holdout.py.
path: {dataset_root}
train: images/train
val: images/val

names:
  0: wheel

kpt_shape: [3, 3]
flip_idx: [1, 0, 2]
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def sha256_file(path: Path) -> str | None:
    if not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def source_manifest_entries(source_root: Path) -> list[dict[str, Any]]:
    paths: list[Path] = []
    for relative in [Path("images"), Path("annotations"), *PROVENANCE_CANDIDATES]:
        candidate = source_root / relative
        if candidate.is_file():
            paths.append(candidate)
        elif candidate.is_dir():
            paths.extend(sorted(path for path in candidate.rglob("*") if path.is_file()))
    entries: list[dict[str, Any]] = []
    for path in sorted(set(paths)):
        entries.append(
            {
                "path": path.relative_to(source_root).as_posix(),
                "size_bytes": path.stat().st_size,
                "sha256": sha256_file(path),
            }
        )
    return entries


def source_manifest_sha256(source_root: Path) -> str:
    canonical = json.dumps(
        source_manifest_entries(source_root),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def load_source_provenance(source_root: Path) -> tuple[Path | None, dict[str, Any]]:
    for relative in PROVENANCE_CANDIDATES:
        candidate = source_root / relative
        if candidate.is_file():
            return candidate, read_json(candidate)
    return None, {}


def validate_production_provenance(provenance: dict[str, Any]) -> list[str]:
    """Require explicit human-labelled AR-device provenance for production holdout.

    Existing smoke/test batches intentionally do not satisfy this contract.
    A real production holdout should carry e.g.:

        {
          "source_type": "android_ar_device_human_labelled",
          "label_type": "human_reviewed",
          "capture_device": "Pixel 8 Pro",
          "annotator": "...",
          "review_status": "accepted"
        }
    """

    failures: list[str] = []
    source_type = str(provenance.get("source_type", "")).strip()
    label_type = str(provenance.get("label_type", "")).strip()
    review_status = str(provenance.get("review_status", "")).strip()
    capture_device = str(provenance.get("capture_device", "")).strip()
    capture_app_version = str(provenance.get("capture_app_version", "")).strip()
    capture_date_utc = str(provenance.get("capture_date_utc", "")).strip()
    annotator = str(provenance.get("annotator", "")).strip()
    reviewer = str(provenance.get("reviewer", "")).strip()

    if not schema_version_matches(provenance.get("schema_version"), EXPECTED_PROVENANCE_SCHEMA_VERSION):
        failures.append(
            f"schema_version must be {EXPECTED_PROVENANCE_SCHEMA_VERSION}, "
            f"got {provenance.get('schema_version', 'missing')}"
        )
    if source_type not in PRODUCTION_SOURCE_TYPES:
        failures.append(
            "source_type must be one of "
            f"{sorted(PRODUCTION_SOURCE_TYPES)}, got {source_type or 'missing'}"
        )
    if label_type != PRODUCTION_LABEL_TYPE:
        failures.append(f"label_type must be {PRODUCTION_LABEL_TYPE}, got {label_type or 'missing'}")
    if review_status != "accepted":
        failures.append(f"review_status must be accepted, got {review_status or 'missing'}")
    if is_placeholder(capture_device):
        failures.append("capture_device is required for production AR holdout provenance")
    if is_placeholder(capture_app_version):
        failures.append("capture_app_version is required for production AR holdout provenance")
    if is_placeholder(capture_date_utc) or not is_valid_utc_date(capture_date_utc):
        failures.append("capture_date_utc must be a real UTC date in YYYY-MM-DD format")
    if is_placeholder(annotator):
        failures.append("annotator is required for production AR holdout provenance")
    if is_placeholder(reviewer):
        failures.append("reviewer is required for production AR holdout provenance")
    if annotator and reviewer and annotator == reviewer:
        failures.append("annotator and reviewer must be different people/accounts")
    return failures


def finite_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(float(value))


def point2(value: Any) -> bool:
    return isinstance(value, list) and len(value) == 2 and all(finite_number(item) for item in value)


def validate_production_wheel(wheel: Any, *, relative: str, index: int) -> list[str]:
    prefix = f"{relative}:wheel[{index}]"
    if not isinstance(wheel, dict):
        return [f"{prefix}: wheel must be an object"]
    failures: list[str] = []
    bbox = wheel.get("bbox_xyxy")
    bbox_xyxy: tuple[float, float, float, float] | None = None
    if not isinstance(bbox, list) or len(bbox) != 4 or not all(finite_number(item) for item in bbox):
        failures.append(f"{prefix}: bbox_xyxy must be 4 finite numbers")
    else:
        x1, y1, x2, y2 = [float(item) for item in bbox]
        if x2 <= x1 or y2 <= y1:
            failures.append(f"{prefix}: bbox_xyxy must have positive area")
        else:
            bbox_xyxy = (x1, y1, x2, y2)
    points = wheel.get("points")
    if not isinstance(points, dict):
        failures.append(f"{prefix}: points must be an object")
    else:
        for name in PRODUCTION_REQUIRED_POINTS:
            point = points.get(name)
            if not point2(point):
                failures.append(f"{prefix}: point {name} must be [x, y] finite numbers")
            elif bbox_xyxy is not None:
                x1, y1, x2, y2 = bbox_xyxy
                x, y = [float(item) for item in point]
                if x < x1 or x > x2 or y < y1 or y > y2:
                    failures.append(f"{prefix}: point {name} must lie inside bbox_xyxy")
    return failures


def validate_production_annotations(source_root: Path) -> list[str]:
    """Require versioned, structurally valid annotation JSON for production evidence."""

    images = source_root / "images"
    annotations = source_root / "annotations"
    failures: list[str] = []
    if not annotations.is_dir():
        return [f"missing annotations directory: {annotations}"]
    image_names = (
        {path.name for path in images.rglob("*") if path.is_file()}
        if images.is_dir()
        else set()
    )
    annotation_files = sorted(path for path in annotations.rglob("*.json") if path.is_file())
    if not annotation_files:
        return [f"missing annotation JSON files: {annotations}"]
    for path in annotation_files:
        relative = path.relative_to(annotations).as_posix()
        stem = path.stem
        payload = read_json(path)
        if not payload:
            failures.append(f"{relative}: annotation JSON must be a non-empty object")
            continue
        if not schema_version_matches(payload.get("schema_version"), EXPECTED_ANNOTATION_SCHEMA_VERSION):
            failures.append(
                f"{relative}: schema_version must be {EXPECTED_ANNOTATION_SCHEMA_VERSION}, "
                f"got {payload.get('schema_version', 'missing')}"
            )
        frame_id = payload.get("frame_id")
        if not isinstance(frame_id, str) or not frame_id:
            failures.append(f"{relative}: frame_id is required")
        elif frame_id != stem:
            failures.append(f"{relative}: frame_id must match annotation stem, got {frame_id}")
        image_name = payload.get("image")
        if not isinstance(image_name, str) or not image_name:
            failures.append(f"{relative}: image is required")
        elif Path(image_name).name != image_name:
            failures.append(f"{relative}: image must be a filename, got {image_name}")
        else:
            if image_names and image_name not in image_names:
                failures.append(f"{relative}: image file is missing, got {image_name}")
            if Path(image_name).stem != stem:
                failures.append(f"{relative}: image stem must match annotation stem, got {image_name}")
        wheels = payload.get("wheels")
        if not isinstance(wheels, list):
            failures.append(f"{relative}: wheels must be an array")
            continue
        for index, wheel in enumerate(wheels):
            failures.extend(validate_production_wheel(wheel, relative=relative, index=index))
    return failures


def metric(report: dict[str, Any], *keys: str, default: float = 0.0) -> float:
    cur: Any = report
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    try:
        return float(cur)
    except (TypeError, ValueError):
        return default


def integer_count(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def strict_count(report: dict[str, Any], key: str, failures: list[str]) -> int:
    counts = report.get("counts", {}) if isinstance(report.get("counts"), dict) else {}
    value = counts.get(key)
    if not integer_count(value):
        failures.append(f"count_not_integer:{key}:{value if value is not None else 'missing'}")
        return 0
    return value


def evaluate_holdout_metrics(
    report: dict[str, Any],
    *,
    min_map50: float,
    min_oks: float,
    max_fn: float,
    min_images: int,
    min_gt_wheels: int,
) -> dict[str, Any]:
    map50 = metric(report, "metrics_bbox", "mAP50")
    oks = metric(report, "oks", "mean")
    fn = metric(report, "rates", "false_negative_rate", default=1.0)
    failures: list[str] = []
    images = strict_count(report, "images", failures)
    gt_wheels = strict_count(report, "gt_wheels", failures)
    if images < min_images:
        failures.append(f"images:{images}<{min_images}")
    if gt_wheels < min_gt_wheels:
        failures.append(f"gt_wheels:{gt_wheels}<{min_gt_wheels}")
    if map50 < min_map50:
        failures.append(f"bbox_mAP50:{map50:.3f}<{min_map50:.3f}")
    if oks < min_oks:
        failures.append(f"OKS:{oks:.3f}<{min_oks:.3f}")
    if fn > max_fn:
        failures.append(f"FN:{fn:.3f}>{max_fn:.3f}")
    return {
        "ok": not failures,
        "failures": failures,
        "thresholds": {
            "min_map50": min_map50,
            "min_oks": min_oks,
            "max_fn": max_fn,
            "min_images": min_images,
            "min_gt_wheels": min_gt_wheels,
        },
        "metrics": {
            "bbox_mAP50": map50,
            "oks_mean": oks,
            "false_negative_rate": fn,
            "images": images,
            "gt_wheels": gt_wheels,
        },
    }


def build_converter_cmd(args: argparse.Namespace) -> list[str]:
    return [
        sys.executable,
        "src/convert_keypoint_incoming_to_yolo_pose.py",
        "--source-root",
        str(args.source_root),
        "--dataset-root",
        str(args.dataset_root),
        "--source-name",
        args.source_name,
        "--val-ratio",
        "1.0",
        "--seed",
        str(args.seed),
        "--max-skip-ratio",
        str(args.max_skip_ratio),
        "--max-warning-ratio",
        str(args.max_warning_ratio),
        "--fail-on-quality-gate",
        "--overwrite",
    ]


def build_eval_cmd(args: argparse.Namespace) -> list[str]:
    return [
        sys.executable,
        "src/eval_keypoints.py",
        "--model",
        str(args.model),
        "--data",
        str(args.config_out),
        "--split",
        "val",
        "--device",
        args.device,
        "--conf",
        str(args.conf),
        "--iou",
        str(args.iou),
        "--max-det",
        str(args.max_det),
        "--output",
        str(args.eval_out),
        "--worst-n",
        str(args.worst_n),
    ]


def write_status(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--dataset-root", type=Path, default=DEFAULT_DATASET_ROOT)
    parser.add_argument("--config-out", type=Path, default=DEFAULT_CONFIG_OUT)
    parser.add_argument("--eval-out", type=Path, default=DEFAULT_EVAL_OUT)
    parser.add_argument("--status-out", type=Path, default=DEFAULT_STATUS_OUT)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--source-name", default="ar_device_holdout")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--conf", type=float, default=0.50)
    parser.add_argument("--iou", type=float, default=0.45)
    parser.add_argument("--max-det", type=int, default=20)
    parser.add_argument("--worst-n", type=int, default=20)
    parser.add_argument("--max-skip-ratio", type=float, default=0.02)
    parser.add_argument("--max-warning-ratio", type=float, default=0.05)
    parser.add_argument("--min-map50", type=float, default=0.85)
    parser.add_argument("--min-oks", type=float, default=0.80)
    parser.add_argument("--max-fn", type=float, default=0.10)
    parser.add_argument("--min-images", type=int, default=50)
    parser.add_argument("--min-gt-wheels", type=int, default=80)
    parser.add_argument(
        "--no-require-production-provenance",
        action="store_true",
        help=(
            "Allow synthetic/plugin-smoke batches. Do not use this for the "
            "production AR-device holdout gate."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    status: dict[str, Any] = {
        "ok": False,
        "source_root": str(args.source_root),
        "dataset_root": str(args.dataset_root),
        "config": str(args.config_out),
        "eval": str(args.eval_out),
        "model": str(args.model),
        "stage": "input",
    }

    if not args.source_root.is_dir():
        status["failure_reason"] = f"missing source root: {args.source_root}"
        write_status(args.status_out, status)
        print(status["failure_reason"])
        print(f"status={args.status_out}")
        return 2
    if not (args.source_root / "images").is_dir() or not (args.source_root / "annotations").is_dir():
        status["failure_reason"] = "source root must contain images/ and annotations/"
        write_status(args.status_out, status)
        print(status["failure_reason"])
        print(f"status={args.status_out}")
        return 2
    status["source_manifest_sha256"] = source_manifest_sha256(args.source_root)
    provenance_path, provenance = load_source_provenance(args.source_root)
    status["provenance_path"] = str(provenance_path) if provenance_path else None
    status["provenance"] = provenance
    if not args.no_require_production_provenance:
        provenance_failures = validate_production_provenance(provenance)
        if provenance_path is None:
            provenance_failures.insert(0, "missing metadata/provenance.json or metadata/source_info.json")
        if provenance_failures:
            status["stage"] = "provenance"
            status["failure_reason"] = "production_provenance_failed"
            status["provenance_failures"] = provenance_failures
            write_status(args.status_out, status)
            print(status["failure_reason"])
            for failure in provenance_failures:
                print(f"- {failure}")
            print(f"status={args.status_out}")
            return 2
        annotation_failures = validate_production_annotations(args.source_root)
        if annotation_failures:
            status["stage"] = "annotation_schema"
            status["failure_reason"] = "production_annotation_schema_failed"
            status["annotation_failures"] = annotation_failures[:100]
            write_status(args.status_out, status)
            print(status["failure_reason"])
            for failure in annotation_failures[:20]:
                print(f"- {failure}")
            print(f"status={args.status_out}")
            return 2
    if not args.model.is_file():
        status["failure_reason"] = f"missing model: {args.model}"
        write_status(args.status_out, status)
        print(status["failure_reason"])
        print(f"status={args.status_out}")
        return 2

    write_dataset_config(args.config_out, args.dataset_root)

    status["stage"] = "convert"
    converter_cmd = build_converter_cmd(args)
    status["converter_cmd"] = converter_cmd
    converter = subprocess.run(converter_cmd, check=False)
    status["converter_returncode"] = converter.returncode
    conversion_report_path = args.dataset_root / "metadata" / "conversion_report.json"
    status["conversion_report"] = str(conversion_report_path)
    status["conversion"] = read_json(conversion_report_path)
    if converter.returncode != 0:
        status["failure_reason"] = "converter_failed"
        write_status(args.status_out, status)
        print(f"status={args.status_out}")
        return converter.returncode

    status["stage"] = "eval"
    eval_cmd = build_eval_cmd(args)
    status["eval_cmd"] = eval_cmd
    evaluation = subprocess.run(eval_cmd, check=False)
    status["eval_returncode"] = evaluation.returncode
    status["eval_report"] = str(args.eval_out)
    status["eval_report_sha256"] = sha256_file(args.eval_out)
    eval_report = read_json(args.eval_out)
    status["evaluation"] = evaluate_holdout_metrics(
        eval_report,
        min_map50=args.min_map50,
        min_oks=args.min_oks,
        max_fn=args.max_fn,
        min_images=args.min_images,
        min_gt_wheels=args.min_gt_wheels,
    )
    if evaluation.returncode != 0:
        status["failure_reason"] = "eval_failed"
        write_status(args.status_out, status)
        print(f"status={args.status_out}")
        return evaluation.returncode

    status["stage"] = "done"
    status["ok"] = bool(status["evaluation"]["ok"])
    if not status["ok"]:
        status["failure_reason"] = "holdout_quality_gate_failed"
    write_status(args.status_out, status)
    print(
        f"ok={status['ok']} "
        f"metrics={status['evaluation']['metrics']} "
        f"failures={status['evaluation']['failures']}"
    )
    print(f"eval={args.eval_out}")
    print(f"status={args.status_out}")
    return 0 if status["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
